/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Duty {
  _id: string;
  name: string;
  description: string;
  location: {
    [k: string]: unknown;
  };
  startTime: string;
  endTime: string;
  minRank: number;
  maxRank: number;
  constraints: string[];
  soldiersRequired: number;
  value: number;
  soldiers: string[];
  status: string;
  statusHistory: {
    status: string;
    date: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
