/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Soldier {
  _id: string;
  name: string;
  rank: {
    name: string;
    value: number;
    [k: string]: unknown;
  };
  limitations: string[];
  createdAt: string;
  updatedAt: string;
  [k: string]: unknown;
}
